packages:
  - ./
  # restore this line to use a local dev copy of stellar-contracts
  # - ../stellar-contracts
# For local development with in-progress changes to stellar-contracts,
# be sure to:
#  - add the package link above.
#  - Also use the 'overrides' below instead of 'overridesDev'.
#  - don't commit these changes!
#  - run `pnpm install` after changing these. 
#  - run `pnpm install` before committing!!!!!

packageManagerStrictVersion: true

# Keep overridesDev: for normal development.   
# Change to 'overrides' link only if needed
overridesDev:
# overrides:
  "@donecollectively/stellar-contracts": "link:../stellar-contracts"
