#!/usr/bin/env bash
startTime=$(date)

. ./node_modules/@donecollectively/stellar-contracts/scripts/support.sh

# set -e # exit on error
#//! EXPECTS to be run in context of `pnpm exec`

playStartSound
{
    pushd dist.overlay >/dev/null
    find . -type f | while read a ; do {
        cp $a ../dist/$a    
        touch ../dist/$a    
    } done
    popd >/dev/null

# echo "tsc --traceResolution -p ./tsconfig.dts.json"
# tsc --traceResolution -p ./tsconfig.dts.json
# exit
    inBackground "typecheck all, create .d.ts types for all packages" \
        tsc -p ./tsconfig.all.dts.json  &

    inBackground "build docs" \
        pnpm docs:generate &
}  

{
    rollup \
      --config rollup.config.ts \
      --importAttributesKey "with" \
      --configPlugin 'esbuild={sourcemap:true,supported:{"import-assertions":false},loaders:{".json": "json"}, target: "esnext", tsconfig:"./tsconfig.rollupconfig.json"}' \
      $* && playProgressSound
} || logProblemWith "dAPI build with rollup"

wait
# Copy typeInfo.d.ts files to dist/types/ for api-extractor
find src -type d | tail -n +2 | while read a ; do { mkdir -p dist/types/$a ; } done
find src -name \*.typeInfo.d.ts | grep -v '/tests/' | while read a ; do { cp $a dist/types/$a ; } done

echo "build started at  $startTime"
date
exitIfError
playCheckpointSound


echo -n "build finished at "
date
# inBackground "dAPI docs" api-extractor run --local --verbose --diagnostics &
inBackground "dAPI docs" api-extractor run --local --verbose &

wait
echo "build started at  $startTime"
echo "build finished at $(date)"
exitIfError

playSuccessSound

# to debug rollup plugins:
#   pnpm exec node --inspect-brk \
#      node_modules/rollup/dist/bin/rollup \
#         --config rollup.config.ts \
#         --configPlugin 'esbuild={loaders:{".json": "json"}, target: "esnext", tsconfig:"./tsconfig.rollupconfig.json"}'
